### ISSUE TITLE
Fix pan limits, fix pan listener on contentAncor, fix zoom into cursor location

### ISSUE THREAD

**Issue by TheodoreJBieber** [linuxboss182/SoftEng-2017#125]

**Comment by linuxboss182** [comment]
We should also change the listener, it shouldn't be on the imageView it should be on the contentAncor.

Right now if we pan far, we can't pan back because we can only pan from imageView.

In addition to this, we need to fix the zoom to zoom into center of screen/cursor position. 

@me will work on this
